name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        python connect4.py
        y
        \n
        5
        \n
        5
        \n
        5
        \n
        5
        \n
        5
        \n
        6
        \n
        6
        \n
        6
        \n
        6
        \n
        6
        \n
        6
        \n
        7
        \n
        7
        \n
        7
        \n
        7
